---
apiVersion: v1
kind: Pod
metadata:
  name: "debug"
  namespace: default
  labels:
    app: "debug"
spec:
  containers:
    - name: debug
      image: nicolaka/netshoot:latest
      command: ["tail"]
      args: ["/dev/random"]
      imagePullPolicy: Always
