apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "name": "bridge-conf",
      "bridge": "eb",
      "isGateway": true,
      "ipMasq": true,
      "ipam": {
      		"type": "host-local",
      		"ranges": [
      			[
      				{
      					"subnet": "10.10.0.0/24",
      					"rangeStart": "10.10.0.20",
      					"rangeEnd": "10.10.0.50"
      				}
      			]
      		],
          "routes": [
            {"dst": "0.0.0.0/0"}
          ],
          "dataDir": "/run/kube-edge/ipam-state"
      	}
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: host-conf
spec:
  config: |-
    {
      "name": "host-conf",
      "type": "host-device",
      "device": "enp0s9",
      "ipam": {
        "type": "static",
        "addresses": [
            {
              "address": "172.17.16.50/24",
              "gateway": "172.17.16.1"
            }
          ]
      }
    }